server:
  # debug release test
  model: release
  port: 8888
  cors: true
  tls:
    enable: false
    key-file: ./default.key
    cert-file: ./default.pem
  # 机器终端操作回放文件存储路径
  machine-rec-path: ./rec
jwt:
  # jwt key，不设置默认使用随机字符串
  key: 
  # 过期时间单位分钟
  expire-time: 1440
# 资源密码aes加密key
aes:
  key: 1111111111111111
mysql:
  host: 192.168.22.30:3306
  username: root
  password: Hc_2023!
  db-name: mayfly_go
  config: charset=utf8&loc=Local&parseTime=true
  max-idle-conns: 5
hcmysql:
  host: 192.168.22.30:3306
  username: root
  password: Hc_2023!
  db-name: hcdb
  config: charset=utf8&loc=Local&parseTime=true
  max-idle-conns: 5
# 若同时部署多台机器，则需要配置redis信息用于缓存权限码、验证码、公私钥等
redis:
  host: 192.168.22.30
  port: 6379
  passsord:
  db: 0
log:
   # 日志等级, trace, debug, info, warn, error, fatal
  level: info
  # file:
  #   path: ./
  #   name: mayfly-go.log